package com.droiddeck.launcher.ui

import androidx.compose.runtime.Composable

internal class PreviewCase(val name: String, val content: @Composable () -> Unit) {
    override fun toString() = name
}

internal val screenPreviewCases = listOf(
    PreviewCase("AlternateTheme") { AlternateThemePreview() },
    PreviewCase("Launcher") { LauncherPreview() },
    PreviewCase("RuntimeMissing") { RuntimeMissingPreview() },
    PreviewCase("RuntimeDownloading") { RuntimeDownloadingPreview() },
    PreviewCase("Library") { LibraryPreview() },
    PreviewCase("EmptyLibrary") { EmptyLibraryPreview() },
    PreviewCase("GameDetails") { GameDetailsPreview() },
    PreviewCase("Desktop") { DesktopPreview() },
    PreviewCase("Emulator") { EmulatorPreview() },
    PreviewCase("Setup") { SetupPreview() },
    PreviewCase("ControllerMapping") { ControllerMappingPreview() },
    PreviewCase("GpuDrivers") { GpuDriversPreview() },
    PreviewCase("Protons") { ProtonsPreview() },
    PreviewCase("ProtonDownload") { ProtonDownloadPreview() },
    PreviewCase("ProtonsEmpty") { ProtonsEmptyPreview() },
    PreviewCase("Drivers") { DriversPreview() },
    PreviewCase("Loading") { LoadingPreview() },
    PreviewCase("SessionStarting") { SessionStartingPreview() },
    PreviewCase("SessionError") { SessionErrorPreview() },
    PreviewCase("Keyboard") { KeyboardPreview() },
    PreviewCase("Hud") { HudPreview() },
    PreviewCase("WirelessAdb") { WirelessAdbPreview() },
    PreviewCase("ProcessLimit") { ProcessLimitPreview() },
    PreviewCase("AddApp") { AddAppPreview() },
    PreviewCase("EditApp") { EditAppPreview() },
    PreviewCase("Confirmation") { ConfirmationPreview() },
    PreviewCase("CustomResolution") { CustomResolutionPreview() },
    PreviewCase("RomsFolder") { RomsFolderPreview() },
    PreviewCase("GameEnvironment") { GameEnvironmentPreview() },
    PreviewCase("WindowsComponents") { WindowsComponentsPreview() },
    PreviewCase("Controls") { ControlsPreview() },
    PreviewCase("Widgets") { WidgetsPreview() },
    PreviewCase("Art") { ArtPreview() },
    PreviewCase("Cursor") { CursorPreview() },
    PreviewCase("SteamDisplay") { SteamDisplayPreview() },
    PreviewCase("SteamControls") { SteamControlsPreview() },
    PreviewCase("SteamGames") { SteamGamesPreview() },
    PreviewCase("SteamAudio") { SteamAudioPreview() },
    PreviewCase("SteamSession") { SteamSessionPreview() },
    PreviewCase("SteamSteam") { SteamSteamPreview() },
    PreviewCase("DesktopSettings") { DesktopSettingsPreview() },
    PreviewCase("DrawerController") { DrawerControllerPreview() },
    PreviewCase("DrawerSecondScreen") { DrawerSecondScreenPreview() },
    PreviewCase("DrawerDisplay") { DrawerDisplayPreview() },
    PreviewCase("DrawerEffects") { DrawerEffectsPreview() },
    PreviewCase("DrawerGames") { DrawerGamesPreview() },
    PreviewCase("DrawerSession") { DrawerSessionPreview() },
    PreviewCase("Performance") { PerformancePreview() },
    PreviewCase("Components") { ComponentsPreview() },
    PreviewCase("ComponentsLoading") { ComponentsLoadingPreview() },
    PreviewCase("GpuComponents") { GpuComponentsPreview() },
    PreviewCase("Updates") { UpdatesPreview() },
    PreviewCase("UpdatesDownloading") { UpdatesDownloadingPreview() },
    PreviewCase("UpdatesError") { UpdatesErrorPreview() },
    PreviewCase("Store") { StorePreview() },
    PreviewCase("DeveloperDisplay") { DeveloperDisplayPreview() },
    PreviewCase("AppDisplay") { AppDisplayPreview() },
    PreviewCase("AndroidApps") { AndroidAppsPreview() },
    PreviewCase("SetupController") { SetupControllerPreview() },
    PreviewCase("SetupSession") { SetupSessionPreview() },
    PreviewCase("SetupLauncher") { SetupLauncherPreview() },
)
