#!/bin/bash
# Compiles the test shaders into C arrays (tests/smoke_spv.h). Needs glslangValidator.
set -eu
cd "$(dirname "$0")"
out=smoke_spv.h
echo "/* Generated by gen_shaders.sh from shaders/ - do not edit. */" > $out
for s in shaders/*.comp shaders/*.vert shaders/*.frag; do
    name=$(basename "$s" | tr . _)
    glslangValidator -V --vn "spv_$name" -o tmp.h "$s" >/dev/null
    grep -v '^ *//' tmp.h | sed 's/^const uint32_t/static const uint32_t/' >> $out
    rm -f tmp.h
done
